### PR TITLE
Rocky preprod

### PR DESCRIPTION
**Pull request by JohnGarbutt**

### CODE REVIEW

**Review by paulbrowne — COMMENTED** [review]
A thought on this is that we're probably going to need to move the Ironic WL provisioning and maybe cleaning+inspection networks back onto the 1GbE interface rather than the LACP 25GbE bond in the controller Kayobe group_vars

**Review by JohnGarbutt — COMMENTED** [review]
FWIW, this all looks good to me.

**Comment by JohnGarbutt** [comment]
Maybe we should branch this now, and do a PR into rock-preprod?

**Comment by paulbrowne** [comment]
Oh yeah, this PR is against rocky stable. Lets PR this into rocky-preprod instead.

**Comment by paulbrowne** [comment]
Closing this for now, further pre-prod deploy commits will go into rocky-preprod-deploy to be merged into rocky-preprod.

**Pull request closed without merging**
